repos:
  - repo: local
    hooks:
      - id: black
        name: Black
        entry: black
        language: system
        types: [python]
        files: ^Day9/(app|tests)/.*\.py$

      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        files: ^Day9/(app|tests)/.*\.py$

      - id: flake8
        name: Flake8
        entry: flake8
        language: system
        types: [python]
        files: ^Day9/(app|tests)/.*\.py$
        args:
          - --config=Day9/.flake8

      - id: mypy
        name: mypy
        entry: bash -c 'cd Day9 && mypy app'
        language: system
        pass_filenames: false
        files: ^Day9/app/.*\.py$
