import {useEffect,useState} from "react";
import {useFieldArray,useForm} from "react-hook-form";
import {zodResolver} from "@hookform/resolvers/zod";
import {useDropzone} from "react-dropzone";
import {Link} from "react-router-dom";
import {Check,ChevronLeft,ChevronRight,FileImage,Paperclip,Plus,Trash2,UploadCloud} from "lucide-react";
import {getAllUsers,getCurrentUser} from "../../services/authService";
import {createTask,deleteTask,getTasks,uploadTaskAttachment} from "../../services/taskService";
import {getProjects} from "../../services/projectService";
import {taskSchema,stepFields} from "../../schemas/taskSchema";
import Button from "../../components/ui/Button";import Input from "../../components/ui/Input";import Select from "../../components/ui/Select";import Textarea from "../../components/ui/Textarea";import Table from "../../components/ui/Table";import Dropdown from "../../components/ui/Dropdown";import {useToast} from "../../components/ui/Toast";
const defaults={title:"",description:"",status:"Pending",priority:"Medium",project_id:"",category_id:"",assignee_id:"",due_date:"",checklist:[]};
const steps=[{title:"Task details",description:"Define the work"},{title:"Planning",description:"Project and ownership"},{title:"Checklist & upload",description:"Break down and attach"}];
function Tasks(){const[user,setUser]=useState(null),[tasks,setTasks]=useState([]),[projects,setProjects]=useState([]),[users,setUsers]=useState([]),[filters,setFilters]=useState({status:"",priority:""}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[step,setStep]=useState(0),[attachment,setAttachment]=useState(null),[preview,setPreview]=useState(""),[error,setError]=useState("");const{push}=useToast();const isAdmin=user?.role==="admin";const{register,control,handleSubmit,trigger,reset,watch,formState:{errors}}=useForm({defaultValues:defaults,resolver:zodResolver(taskSchema),mode:"onBlur"});const{fields,append,remove}=useFieldArray({control,name:"checklist"});const selectedProject=projects.find(p=>String(p.id)===String(watch("project_id")));
async function loadTasks(){if(!user)return;try{setLoading(true);const params={};if(filters.status)params.status=filters.status;if(filters.priority)params.priority=filters.priority;setTasks(await getTasks(params))}catch(e){setError(e.response?.data?.detail||"Unable to load tasks.")}finally{setLoading(false)}}
useEffect(()=>{(async()=>{try{const current=await getCurrentUser();setUser(current);const req=[getTasks(),getProjects()];if(current.role==="admin")req.push(getAllUsers());const[td,pd,ud=[]]=await Promise.all(req);setTasks(td);setProjects(pd);setUsers(ud);if(pd.length)reset({...defaults,project_id:String(pd[0].id)})}catch(e){setError(e.response?.data?.detail||"Unable to load tasks.")}finally{setLoading(false)}})()},[reset]);useEffect(()=>{if(user)loadTasks()},[filters.status,filters.priority]);
async function next(event){if(event){event.preventDefault();event.stopPropagation()}const valid=await trigger(stepFields[step]);if(valid)setStep(s=>Math.min(2,s+1))}function back(){setStep(s=>Math.max(0,s-1))}async function onFormSubmit(event){if(step<2){event.preventDefault();event.stopPropagation();return}await handleSubmit(submit)(event)}function onDrop(files){const file=files[0];if(!file)return;setAttachment(file);setPreview(file.type.startsWith("image/")?URL.createObjectURL(file):"")}const{getRootProps,getInputProps,isDragActive}=useDropzone({onDrop,multiple:false,accept:{"image/jpeg":[".jpg",".jpeg"],"image/png":[".png"],"image/webp":[".webp"],"application/pdf":[".pdf"]},maxSize:5*1024*1024});
async function submit(data){try{setSaving(true);setError("");const payload={title:data.title,description:data.description||null,status:data.status,priority:data.priority,category_id:data.category_id?Number(data.category_id):null,project_id:Number(data.project_id),due_date:data.due_date?new Date(data.due_date).toISOString():null,checklist:data.checklist.filter(item=>item.title.trim()).map((item,index)=>({title:item.title.trim(),position:index})),...(isAdmin&&data.assignee_id?{assignee_id:Number(data.assignee_id)}:{})};const task=await createTask(payload);if(attachment)await uploadTaskAttachment(task.id,attachment);push({title:"Task created",message:`Task #${task.id} was created successfully.`});reset({...defaults,project_id:String(data.project_id)});setStep(0);setAttachment(null);setPreview("");await loadTasks()}catch(e){setError(e.response?.data?.detail||"Unable to create task.");push({title:"Creation failed",message:e.response?.data?.detail||"Please try again.",type:"error"})}finally{setSaving(false)}}
async function handleDelete(id){if(!window.confirm(`Delete task #${id}?`))return;try{await deleteTask(id);setTasks(t=>t.filter(x=>x.id!==id));push({title:"Task deleted",message:`Task #${id} was removed.`})}catch(e){push({title:"Delete failed",message:e.response?.data?.detail||"Unable to delete task.",type:"error"})}}
return <div className="workspace-page"><div className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-start"><div><span className="eyebrow">TASK WORKSPACE</span><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-900 dark:text-white">{isAdmin?"Task management":"My tasks"}</h1><p className="mt-2 text-slate-500 dark:text-slate-400">Validated multi-step task creation with dynamic checklists, drag-and-drop attachments and role-aware assignment.</p></div><Dropdown label="Quick actions" items={[{label:"Reset task form",onClick:()=>{reset(defaults);setStep(0);setAttachment(null);setPreview("")}},{label:"Refresh task list",onClick:loadTasks}]}/></div>{error&&<div className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700 dark:border-red-900 dark:bg-red-950/30 dark:text-red-300" role="alert">{error}</div>}
<section className="workspace-card mb-7 p-5 md:p-7"><div className="mb-6"><div className="stepper" aria-label="Task creation steps">{steps.map((item,index)=><div key={item.title} className={`stepper-item ${index===step?"active":""}`} aria-current={index===step?"step":undefined}><span className="stepper-number">{index<step?<Check size={15}/>:index+1}</span><div><strong className="block text-sm">{item.title}</strong><span className="hidden text-xs sm:block">{item.description}</span></div></div>)}</div></div><form onSubmit={onFormSubmit} onKeyDown={event=>{if(event.key==="Enter"&&event.target.tagName!=="TEXTAREA"){event.preventDefault()}}} noValidate>{step===0&&<div className="grid gap-5 md:grid-cols-2"><div className="md:col-span-2"><Input id="title" label="Task title" placeholder="e.g. Implement payment webhook" {...register("title")} error={errors.title?.message}/></div><div className="md:col-span-2"><Textarea id="description" label="Description" placeholder="Describe the expected outcome and acceptance criteria" {...register("description")} error={errors.description?.message}/></div><Select id="status" label="Status" {...register("status")} error={errors.status?.message}><option>Pending</option><option>In Progress</option><option>Completed</option></Select><Select id="priority" label="Priority" {...register("priority")} error={errors.priority?.message}><option>Low</option><option>Medium</option><option>High</option></Select></div>}
{step===1&&<div className="grid gap-5 md:grid-cols-2"><Select id="project_id" label="Project" {...register("project_id")} error={errors.project_id?.message}><option value="">Select a project</option>{projects.map(p=><option key={p.id} value={p.id}>#{p.id} — {p.name}</option>)}</Select><Input id="category_id" label="Category ID (optional)" type="number" min="1" placeholder="e.g. 2" {...register("category_id")}/>{isAdmin?<Select id="assignee_id" label="Assignee" {...register("assignee_id")}><option value="">Unassigned</option>{users.map(u=><option key={u.id} value={u.id}>#{u.id} — {u.username}</option>)}</Select>:<Input id="assignee" label="Assignee" value={`You — ${user?.username||"current user"}`} disabled readOnly/>}<Input id="due_date" label="Due date" type="datetime-local" {...register("due_date")}/><div className="md:col-span-2 rounded-xl bg-slate-50 p-4 text-sm text-slate-600 dark:bg-slate-800/60 dark:text-slate-300"><strong>Ownership rule:</strong> normal users can create tasks only inside projects they own; admins can assign tasks across the workspace.</div></div>}
{step===2&&<div className="grid gap-6 lg:grid-cols-2"><div><div className="mb-3 flex items-center justify-between"><div><h3 className="font-bold text-slate-900 dark:text-white">Dynamic checklist</h3><p className="text-xs text-slate-500">Add or remove implementation steps.</p></div><Button type="button" size="sm" variant="outline" onClick={()=>append({title:""})}><Plus size={15}/> Add step</Button></div><div className="grid gap-3">{fields.map((field,index)=><div className="checklist-row" key={field.id}><Input id={`checklist-${index}`} label={`Step ${index+1}`} {...register(`checklist.${index}.title`)} error={errors.checklist?.[index]?.title?.message}/><Button type="button" variant="ghost" aria-label={`Remove checklist step ${index+1}`} onClick={()=>remove(index)}><Trash2 size={16}/></Button></div>)}</div>{fields.length===0&&<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500 dark:bg-slate-800">No checklist steps. You can add them with the button above.</p>}</div><div><h3 className="mb-3 font-bold text-slate-900 dark:text-white">Attachment & preview</h3><div {...getRootProps({className:`dropzone ${isDragActive?"active":""}`})}><input {...getInputProps()} aria-label="Upload task attachment"/><UploadCloud className="mx-auto mb-3 text-indigo-500" size={34}/><p className="font-semibold text-slate-700 dark:text-slate-200">{isDragActive?"Drop the file here":"Drag & drop or click to browse"}</p><p className="mt-1 text-xs text-slate-500">JPG, PNG, WEBP or PDF · maximum 5 MB</p></div>{attachment&&<div className="mt-4 flex items-center gap-3 rounded-xl border border-slate-200 p-3 dark:border-slate-700">{preview?<img src={preview} alt="Selected task attachment preview" className="preview-image"/>:<FileImage size={40} className="text-slate-400"/>}<div className="min-w-0"><strong className="block truncate text-sm">{attachment.name}</strong><span className="text-xs text-slate-500">{Math.max(1,Math.round(attachment.size/1024))} KB</span></div><Paperclip className="ml-auto text-slate-400" size={18}/></div>}</div></div>}
<div className="mt-7 flex flex-wrap justify-between gap-3 border-t border-slate-200 pt-5 dark:border-slate-700">{step>0?<Button type="button" variant="secondary" onClick={back}><ChevronLeft size={16}/> Back</Button>:<span/>}{step<2?<Button type="button" onClick={event=>next(event)}>Continue <ChevronRight size={16}/></Button>:<Button type="submit" disabled={saving}>{saving?"Creating...":"Create Task"} <Check size={16}/></Button>}</div></form></section>
<section className="workspace-card overflow-hidden"><div className="flex flex-col justify-between gap-4 border-b border-slate-200 p-5 md:flex-row md:items-center dark:border-slate-700"><div><h2 className="text-lg font-bold text-slate-900 dark:text-white">Task list</h2><p className="text-sm text-slate-500 dark:text-slate-400">Filter and manage current workspace tasks.</p></div><div className="flex flex-wrap gap-2"><select aria-label="Filter by status" className="rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900" value={filters.status} onChange={e=>setFilters(f=>({...f,status:e.target.value}))}><option value="">All statuses</option><option>Pending</option><option>In Progress</option><option>Completed</option></select><select aria-label="Filter by priority" className="rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900" value={filters.priority} onChange={e=>setFilters(f=>({...f,priority:e.target.value}))}><option value="">All priorities</option><option>Low</option><option>Medium</option><option>High</option></select></div></div>{loading?<div className="loading-state">Loading tasks...</div>:tasks.length===0?<div className="empty-state">No tasks found for the current filters.</div>:<Table><Table.Head><tr><th className="px-4 py-3">Task</th><th className="px-4 py-3">Project</th><th className="px-4 py-3">Priority</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Due</th><th className="px-4 py-3">Actions</th></tr></Table.Head><Table.Body>{tasks.map(task=><Table.Row key={task.id}><Table.Cell><div className="font-semibold text-slate-900 dark:text-white">{task.title}</div><div className="text-xs text-slate-500">#{task.id}</div></Table.Cell><Table.Cell>#{task.project_id}</Table.Cell><Table.Cell><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold dark:bg-slate-800">{task.priority}</span></Table.Cell><Table.Cell><span className={`badge badge-${task.status.toLowerCase().replaceAll(" ","-")}`}>{task.status}</span></Table.Cell><Table.Cell>{task.due_date?new Date(task.due_date).toLocaleDateString():"—"}</Table.Cell><Table.Cell><div className="flex gap-2"><Link className="button button-secondary" to={`/tasks/${task.id}`}>Open</Link><Button size="sm" variant="danger" onClick={()=>handleDelete(task.id)}><Trash2 size={14}/>Delete</Button></div></Table.Cell></Table.Row>)}</Table.Body></Table>}</section></div>}
export default Tasks;
