import {useEffect,useMemo,useState} from "react";
import {Link,useNavigate,useParams} from "react-router-dom";
import {useForm} from "react-hook-form";
import {zodResolver} from "@hookform/resolvers/zod";
import {CheckCircle2,Paperclip,Trash2} from "lucide-react";
import {getAllUsers,getCurrentUser} from "../services/authService";
import {getProjects} from "../services/projectService";
import {deleteChecklistItem,deleteTask,getTask,getTaskAttachments,updateChecklistItem,updateTask} from "../services/taskService";
import {taskSchema} from "../schemas/taskSchema";
import Button from "../components/ui/Button";
import Input from "../components/ui/Input";
import Select from "../components/ui/Select";
import Textarea from "../components/ui/Textarea";
import Dialog from "../components/ui/Dialog";
import {useToast} from "../components/ui/Toast";

const statusOptions=["Pending","In Progress","Completed"];const priorityOptions=["Low","Medium","High"];
function TaskDetails(){const{taskId}=useParams();const navigate=useNavigate();const[task,setTask]=useState(null),[user,setUser]=useState(null),[projects,setProjects]=useState([]),[users,setUsers]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[deleteOpen,setDeleteOpen]=useState(false),[busyItem,setBusyItem]=useState(null);const{push}=useToast();
const{register,handleSubmit,setValue,watch,formState:{errors}}=useForm({defaultValues:{title:"",description:"",status:"Pending",priority:"Medium",project_id:"",category_id:"",assignee_id:"",due_date:"",checklist:[]},resolver:zodResolver(taskSchema),mode:"onBlur"});
const status=watch("status");
async function initialize(){try{setLoading(true);const[current,data,projectData]=await Promise.all([getCurrentUser(),getTask(taskId),getProjects()]);setUser(current);setTask(data);setProjects(projectData);if(current.role==="admin")setUsers(await getAllUsers());setValue("title",data.title||"");setValue("description",data.description||"");setValue("status",data.status||"Pending");setValue("priority",data.priority||"Medium");setValue("project_id",String(data.project_id??""));setValue("category_id",data.category_id==null?"":String(data.category_id));setValue("assignee_id",data.assignee_id==null?"":String(data.assignee_id));setValue("due_date",data.due_date?data.due_date.slice(0,16):"")}catch(e){setError(e.response?.data?.detail||"Unable to load task.")}finally{setLoading(false)}}
useEffect(()=>{initialize()},[taskId]);
const allowedStatuses=useMemo(()=>{if(!task)return statusOptions;if(task.status==="Pending")return["Pending","In Progress"];if(task.status==="In Progress")return["In Progress","Completed"];return["Completed"]},[task]);
async function submit(data){try{setSaving(true);const payload={title:data.title,description:data.description||null,status:data.status,priority:data.priority,category_id:data.category_id?Number(data.category_id):null,project_id:Number(data.project_id),assignee_id:user?.role==="admin"?(data.assignee_id?Number(data.assignee_id):null):user?.id,due_date:data.due_date?new Date(data.due_date).toISOString():null};const updated=await updateTask(taskId,payload);setTask(updated);push({title:"Task updated",message:`Task #${taskId} was saved.`})}catch(e){setError(e.response?.data?.detail||"Unable to update task.");push({title:"Update failed",message:e.response?.data?.detail||"Unable to update task.",type:"error"})}finally{setSaving(false)}}
async function toggleChecklist(item){try{setBusyItem(item.id);const updated=await updateChecklistItem(taskId,item.id,{completed:!item.completed});setTask(t=>({...t,checklist_items:t.checklist_items.map(x=>x.id===item.id?updated:x)}))}catch(e){push({title:"Checklist update failed",message:e.response?.data?.detail||"Unable to update checklist item.",type:"error"})}finally{setBusyItem(null)}}
async function removeChecklist(item){try{setBusyItem(item.id);await deleteChecklistItem(taskId,item.id);setTask(t=>({...t,checklist_items:t.checklist_items.filter(x=>x.id!==item.id)}));push({title:"Checklist item removed",message:item.title})}catch(e){push({title:"Delete failed",message:e.response?.data?.detail||"Unable to remove item.",type:"error"})}finally{setBusyItem(null)}}
async function confirmDelete(){try{await deleteTask(taskId);push({title:"Task deleted",message:`Task #${taskId} was removed.`});navigate("/dashboard/tasks",{replace:true})}catch(e){setError(e.response?.data?.detail||"Unable to delete task.")}finally{setDeleteOpen(false)}}
if(loading)return <main className="page-shell"><div className="loading-state">Loading task...</div></main>;if(!task)return <main className="page-shell"><div className="alert alert-error">{error||"Task not found."}</div><Link to="/dashboard/tasks">Back to Tasks</Link></main>;
return <main className="page-shell narrow-page"><div className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-start"><div><span className="eyebrow">TASK #{task.id}</span><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-900 dark:text-white">{task.title}</h1><p className="mt-2 text-slate-500 dark:text-slate-400">Update task status, ownership and execution checklist.</p></div><Link className="button button-secondary" to="/dashboard/tasks">Back to Tasks</Link></div>{error&&<div className="alert alert-error">{error}</div>}
<form className="workspace-card grid gap-5 p-5 md:grid-cols-2 md:p-7" onSubmit={handleSubmit(submit)} noValidate><div className="md:col-span-2"><Input id="title" label="Title" {...register("title")} error={errors.title?.message}/></div><div className="md:col-span-2"><Textarea id="description" label="Description" rows="5" {...register("description")} error={errors.description?.message}/></div><Select id="status" label="Status" {...register("status")}><option value={statusOptions[0]} disabled={!allowedStatuses.includes("Pending")}>Pending</option><option value="In Progress" disabled={!allowedStatuses.includes("In Progress")}>In Progress</option><option value="Completed" disabled={!allowedStatuses.includes("Completed")}>Completed</option></Select><Select id="priority" label="Priority" {...register("priority")}><option>Low</option><option>Medium</option><option>High</option></Select><Select id="project_id" label="Project" {...register("project_id")} error={errors.project_id?.message}><option value="">Select project</option>{projects.map(p=><option key={p.id} value={p.id}>#{p.id} — {p.name}</option>)}</Select><Input id="category_id" label="Category ID" type="number" min="1" {...register("category_id")}/>{user?.role==="admin"?<Select id="assignee_id" label="Assignee" {...register("assignee_id")}><option value="">Unassigned</option>{users.map(u=><option key={u.id} value={u.id}>#{u.id} — {u.username}</option>)}</Select>:<Input id="assignee" label="Assignee" value={`You — ${user?.username||"current user"}`} disabled readOnly/>}<Input id="due_date" label="Due date" type="datetime-local" {...register("due_date")}/><div className="md:col-span-2 flex flex-wrap gap-3 border-t border-slate-200 pt-5 dark:border-slate-700"><Button type="submit" disabled={saving}>{saving?"Saving...":"Save Changes"}</Button><Button type="button" variant="danger" onClick={()=>setDeleteOpen(true)}><Trash2 size={16}/> Delete Task</Button></div></form>

<section className="workspace-card mt-6 p-5 md:p-7"><div className="mb-5"><h2 className="text-lg font-bold text-slate-900 dark:text-white">Execution checklist</h2><p className="text-sm text-slate-500">Dynamic checklist items created with the task.</p></div>{!task.checklist_items?.length?<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500 dark:bg-slate-800">No checklist items were added.</p>:<div className="grid gap-3">{task.checklist_items.map(item=><div key={item.id} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3 dark:border-slate-700"><button type="button" aria-label={item.completed?`Mark ${item.title} incomplete`:`Mark ${item.title} complete`} onClick={()=>toggleChecklist(item)} disabled={busyItem===item.id} className="text-indigo-600 disabled:opacity-50">{item.completed?<CheckCircle2/>:<span className="block h-5 w-5 rounded-full border-2 border-slate-300"/>}</button><span className={`flex-1 text-sm ${item.completed?"text-slate-400 line-through":"text-slate-700 dark:text-slate-200"}`}>{item.title}</span><button type="button" aria-label={`Delete ${item.title}`} onClick={()=>removeChecklist(item)} disabled={busyItem===item.id} className="text-red-500"><Trash2 size={16}/></button></div>)}</div>}</section>
<section className="workspace-card mt-6 p-5 md:p-7"><div className="mb-5"><h2 className="text-lg font-bold text-slate-900 dark:text-white">Attachments</h2><p className="text-sm text-slate-500">Uploaded task files and images.</p></div>{!task.attachments?.length?<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500 dark:bg-slate-800">No attachments.</p>:<div className="grid gap-3">{task.attachments.map(file=><a key={file.id} href={`${import.meta.env.VITE_API_URL||"http://127.0.0.1:8000"}${file.file_url}`} target="_blank" rel="noreferrer" className="flex items-center gap-3 rounded-xl border border-slate-200 p-3 hover:bg-slate-50 dark:border-slate-700 dark:hover:bg-slate-800"><Paperclip size={18} className="text-indigo-500"/><span className="flex-1 truncate text-sm font-semibold">{file.original_name}</span><span className="text-xs text-slate-500">Open</span></a>)}</div>}</section>

<Dialog open={deleteOpen} onClose={()=>setDeleteOpen(false)} title="Delete this task?" description="This permanently removes the task and its checklist/attachment records."><div className="flex justify-end gap-3"><Button variant="secondary" onClick={()=>setDeleteOpen(false)}>Cancel</Button><Button variant="danger" onClick={confirmDelete}>Delete permanently</Button></div></Dialog></main>}
export default TaskDetails;
